services:
  ## FOR POSTGRES EXAMPLE ONLY
  postgres-example:
    image: postgres:13
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - db-example-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "localhost", "-p", "5432", "-d", "postgres", "-U", "user1" ]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - airflow

volumes:
  db-example-volume:

networks:
  airflow:
    name: airflow_default
    external: true